version: '3.0'

name: wb-l0

services:
  postgre:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: wbl0password
      POSTGRES_USER: wbl0user
      POSTGRES_DB: wbl0
    ports:
      - 5432:5432

  nats:
    image: nats-streaming:0.25.6-alpine3.18
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 -cid order_cluster"
    ports:
      - 8222:8222